- features/is-analytics-feature/org.wso2.analytics.solutions.is.analytics.feature/src/main/resources/p2.inf
- features/is-analytics-feature/org.wso2.analytics.solutions.is.analytics.feature/src/main/resources/siddhi-files/IS_AUTHENTICATION_COMMON.siddhi
> Siddhi file has changed to handle role filtering in the widgets. To do so, `rolesCommaSeparated` string should have commas on the beginning and the end.
> Fixed an issue with the `p2.inf` file. Where the copy operation failed due to path mismatch.
> Changing siddhi file to handle role filtering, fixing an issue in p2 file

- features/is-analytics-feature/org.wso2.analytics.solutions.is.analytics.feature/src/main/resources/siddhi-files/IS_ANALYTICS_LONG_SESSION.siddhi
> IS_ANALYTICS_LONG_SESSION siddhi spp is amended to calculate the last seven days timestamp of users. Initially, a trigger is sent at the beginning to store the average duration of users for the last seven days in an event table. Then another trigger is sent to update that event table for every 30 minutes.
> Rework Siddhi applications

- components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsAttemptsByType/src/IsAnalyticsAttemptsByType.jsx
- components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsAttemptsOverTime/src/IsAnalyticsAttemptsOverTime.jsx
- components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsCompactSummary/src/IsAnalyticsCompactSummary.jsx
- components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsLoginAttemptsMap/src/IsAnalyticsLoginAttemptsMap.jsx
- components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsMessages/package-lock.json
- components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsMessages/package.json
- components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsMessages/src/IsAnalyticsMessages.jsx
- components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsSummary/src/IsAnalyticsSummary.jsx
- features/is-analytics-feature/org.wso2.analytics.solutions.is.analytics.feature/src/main/resources/dashboards/is-analytics.json
> * The call back function of the `WidgetChannelManager` was not worked before, when there are no data coming from the data provider. Now the functionality is fixed and hence the redundant logic is removed which used to reset data in the widget before the data provider call.
> * The `IsAnalyticsMessages` widget in the `Local Login Attempts` page was set to the widget type of `Overall`, mistakenly. It is now fixed.
> N/A
> Removing redundant logic from widgets

- features/apim-analytics-feature/org.wso2.analytics.solutions.apim.analytics.feature/src/main/resources/p2.inf
This PR will avoid apim widgets and dashboards getting packed inside the SP distribution.
> Remove apim widgets and dashboard from apim analytics feature

- components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsLoginAttemptsMap/src/IsAnalyticsLoginAttemptsMap.jsx
- components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsUserPreferences/package-lock.json
- components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsUserPreferences/package.json
- components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsUserPreferences/src/IsAnalyticsUserPreferences.jsx
> Bump `material-ui` version to `1.5.0` in `IS Analytics User Preferences` widget
> Changing the styles class name to overcome ambiguity.
> N/A
> Bump material-ui version in User Preferences

- components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsSessionCount/src/IsAnalyticsSessionCount.jsx
> Setting appendArray empty in IsAnalyticsSessionCount.jsx in order to avoid the issue in displaying the chart
> Refctoring IsAnalyticsSessionCount.jsx

- components/analytics-solutions-common/org.wso2.analytics.solutions.common/widgets/DateTimeRangePicker/src/CustomTimeRangeSelector.jsx
- components/analytics-solutions-common/org.wso2.analytics.solutions.common/widgets/DateTimeRangePicker/src/DateTimePicker.jsx
Disable selection of equal start and end timestamps in custom time range selector and set the start and end times with difference of 1 day as default values.
**Note: please review, do not merge**
> Disable same start timestamp and end timestamp for custom range selector

- features/ei-analytics-feature/org.wso2.analytics.solutions.ei.analytics.feature/src/main/resources/siddhi-files/EI_Analytics_StatApp.siddhi
Improves the throughput of EI Analytics SIddhi app.
A low throughput was observed for the table insert query for ESBEventTable. Using @Async annotation improves the throughput to some extent.
Only two indexes are required for the ESBEventTable, which also improves the throughput.
> Improving EI analytics siddhi app

- features/is-analytics-feature/org.wso2.analytics.solutions.is.analytics.feature/src/main/resources/siddhi-files/IS_ANALYTICS_SUSPICIOUS_LOGIN.siddhi
> Fix Id 'e3' not defined within scope issue 
> To deploy IS_ANALYTICS_SUSPICIOUS_LOGIN.siddhi app without any error in IS Analytics
> Defined the relevant field within the given scope
> java version "1.8.0_191"
mysql version "5.7.25"
mysql-connector-java-8.0.12
> Fix id e3 not in scope issue

- components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsStatsChart/src/EIAnalyticsStatsChart.jsx
> Fix #160 Mediator name overlaps the chart
> Add css to handle the overlapping
> Add a tooltip with full name of the component
Before
After
> [EIAnalytics] [Mediator Request Count] Fix mediator name overlapping the next div

- components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsMediatorProperties/src/EIAnalyticsMediatorProperties.jsx
> Fix issue #223 Screen goes blank if payload.before and payload.after are undefined
> [EIAnalytics] [MediatorProperties] Check for payload before drawing the MergeView

- components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsStatsChart/src/EIAnalyticsStatsChart.jsx
> Fix issue #222
> Align the total count, success chart and failure chart to center.
> [EIAnalytics] [StatsChart] Fix div alignment

- features/sp-solution-features/org.wso2.analytics.solutions.sp.http.analytics.feature/src/main/resources/templates/http-analytics-solution.json
To fix CURL commands in try-out tutorial dynamic. As default HTTP source does not include receiver.url param, this makes the HTTP source defined to have a URL based on business rules name deployed. Thus Documentation has CURL commands which the user has to edit before using.
Fixes https://github.com/wso2/analytics-solutions/issues/211
By defining a constant URL, the final CURL commands can be given, thus giving better user experience.
Define receiver.url param in default source definition.
`type='http', receiver.url='http://localhost:8280/HttpAnalytics/RequestsStream' , @map(type='json')
`
https://docs.wso2.com/display/SP4xx/HTTP+Analytics needs to be updated with new CURL commands,
Sample:
`curl -v -X POST \  http://localhost:8280/HttpAnalytics/RequestsStream \  -H 'content-type: …
> [HTTP-Analytics-Solution] Make Default HTTP source URL constant for better user experience

- components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsHorizontalBarChart/src/EIAnalyticsHorizontalBarChart.jsx
- components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsTPS/src/EIAnalyticsTPS.jsx
> Fix #240 
> Since the color was set to white, the text was not visible in light theme. I removed the color, So it will be changed according to the theme.
Dark theme
Light theme
> [EIAnalytics] [Widgets] Fix style of "No records found" message

- components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsTPS/src/EIAnalyticsTPS.jsx
> Fix isuue #236 timestamp in tooltip is not human readable
**Screenshots**
Before
After
> [EIAnalytics] [OverallTPS Widget] Show readable date time in tooltip

- components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsMessageTable/src/EIAnalyticsMessageTable.jsx
> Fix issue #227 Message table is not visible when no of rows per page are set more than 5.
> Add a scrollbar for the table.
> [EIAnalytics] [MessageTableWidget] Add scrollbar for the table

- components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsHorizontalBarChart/package.json
- components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsStatsChart/package.json
- components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsTPS/package.json
> Bump react-vizgrammar to latest version V0.8.5 in EIAnalytics Widgets
> [EIAnalytics] [Widgets] Bump react-vizgrammar version

- components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsHorizontalBarChart/package.json
- components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsStatsChart/package.json
- components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsTPS/package.json
> Bump react-vizgrammar version to the latest for EIAnalytics Widgets
> [EIAnalytics] Bump react-vizgrammar version to 0.8.6

- components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsHorizontalBarChart/src/EIAnalyticsHorizontalBarChart.jsx
- components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsMediatorProperties/src/EIAnalyticsMediatorProperties.jsx
- components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsMessageFlow/src/EIAnalyticsMessageFlow.jsx
- components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsMessageTable/src/EIAnalyticsMessageTable.jsx
- components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsStatsChart/src/EIAnalyticsStatsChart.jsx
- components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsTPS/src/EIAnalyticsTPS.jsx
- features/ei-analytics-feature/org.wso2.analytics.solutions.ei.analytics.feature/src/main/resources/dashboards/ei-anlaytics.json
> Currently tenantId is hard coded as "-1234" in all the widgets. Tenant ID has to be read from the dashboard properties. We have changed dashboard JSON structure inorder to achive this.
The change in the common dashboard JSON structure was done in https://github.com/wso2/carbon-dashboards/pull/1144
> Edit EI Dashboard JSON to add tenantId as a dashboard property
> Use tenantId from dashboard properties instead of hard coded tenantId in all widgets
> [EIAnalytics] Get tenantId from dashboard properties instead of hardcoded constants

- features/apim-analytics-feature/org.wso2.analytics.solutions.apim.analytics.feature/src/main/resources/email-notification-siddhi-file/APIM_ALERT_EMAIL_NOTIFICATION.siddhi
- features/apim-analytics-feature/org.wso2.analytics.solutions.apim.analytics.feature/src/main/resources/siddhi-files/APIM_ALERT_CONFIGURATION.siddhi
- features/apim-analytics-feature/org.wso2.analytics.solutions.apim.analytics.feature/src/main/resources/siddhi-files/APIM_ALERT_STAKEHOLDER.siddhi
- features/apim-analytics-feature/org.wso2.analytics.solutions.apim.analytics.feature/src/main/resources/siddhi-files/APIM_EVENT_RECEIVER.siddhi
- features/apim-analytics-feature/org.wso2.analytics.solutions.apim.analytics.feature/src/main/resources/siddhi-files/apim_alert_abnormal_backend_time_0.siddhi
- features/apim-analytics-feature/org.wso2.analytics.solutions.apim.analytics.feature/src/main/resources/siddhi-files/apim_alert_abnormal_request_count_0.siddhi
- features/apim-analytics-feature/org.wso2.analytics.solutions.apim.analytics.feature/src/main/resources/siddhi-files/apim_alert_abnormal_response_time_0.siddhi
- features/apim-analytics-feature/org.wso2.analytics.solutions.apim.analytics.feature/src/main/resources/siddhi-files/apim_alert_health_availability_0.siddhi
Fix in-memory config tables being out of sync with physical tables. Since updates for the configurations are done through store queries from APIM, this can lead to in-memory tables out of sync with physical tables until a restart/ app redeployment
Periodically sync in-memory configuration tables
Use of a trigger every 5 minutes to update or insert in-memory tables from the records selected from physical tables.
N/A
Alter ApiSubAlertConf table with additional index consisting of coloumns 'applicationId', 'apiName', …
> [APIM Analytics] Periodically sync in-memory configuration tables

- features/apim-analytics-feature/org.wso2.analytics.solutions.apim.analytics.feature/src/main/resources/siddhi-files/APIM_API_AVAILABILITY.siddhi
$subject as API creator is changed when the API is modified
N/A
> Remove apiCreator in ApimApiAvailabilityInfo update

- features/apim-analytics-feature/org.wso2.analytics.solutions.apim.analytics.feature/src/main/resources/siddhi-files/apim_alert_health_availability_0.siddhi
>  Fix health alert not sent if threshold response time is not configured

- components/analytics-solutions-common/org.wso2.analytics.solutions.common/widgets/DateTimeRangePicker/src/widget/DateTimePicker.jsx
- components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsAverageSessionDuration/src/IsAnalyticsAverageSessionDuration.jsx
- components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsAverageSessionDuration/src/resources/widgetConf.json
- components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsSessionCountOverTime/src/IsAnalyticsSessionCountOverTime.jsx
- components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsSessionCountOverTime/src/resources/widgetConf.json
- components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsTopLongestSession/src/IsAnalyticsTopLongestSession.jsx
- components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsTopLongestSession/src/resources/widgetConf.json
This PR fixes the following issues in the IS-Analytics dashboard.
- Invalid granularity is selected when selecting 3/6 months in the date range picker.
- No data in Top longest session and average session duration widgets.
- No tenant filtration in widgets
- Missing data in charts.
To fix the data not showing issue in the average session duration widget in MySQL, follow the steps mentioned below.
1. Log on the MySQL console and run the following command to remove `ONLY_FULL_GROUP_BY` from `sql_mode`.
```sql
SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode, 'ONLY_FULL_GROUP_BY,', ''));
```
2. Re-login to the MySQL console.
- …
> Fix issues in IS-Analytics dashboard

- features/is-analytics-feature/org.wso2.analytics.solutions.is.analytics.feature/src/main/resources/siddhi-files/IS_ANALYTICS_SESSION_DATA.siddhi
Avoid the portal graph showing active session count as negative.
When a session termination event is received for a session that is not traced for the creation, analytics should not consider it as it will corrupt the data, making it possible to go negative. We consider this a highly unlikely situation unless analytics is enabled while there are active sessions(remember me, sessions maybe).
(Contributed by Lasantha)
> Fixing the active session count going negative. 

- features/is-analytics-feature/org.wso2.analytics.solutions.is.analytics.feature/src/main/resources/siddhi-files/IS_ANALYTICS_SESSION_DATA.siddhi
> Avoid the portal graph showing active session count as negative.
> When a session termination event is received for a session that is not traced for the creation, analytics should not consider it as it will corrupt the data, making it possible to go negative. We consider this a highly unlikely situation unless analytics is enabled while there are active sessions(remember me, sessions may be).
(Contributed by Lasantha)
> Fixing the active session count going negative.
