wso2/analytics-solutions

pom.xml

This PR fixes the dependencies for Twitter-analytics solution.

Fix twitter-analytics dependencies

---

components/sp-solutions/org.wso2.carbon.sp.solutions.twitter.analytics/widgets/PopularTweets/package-lock.json
components/sp-solutions/org.wso2.carbon.sp.solutions.twitter.analytics/widgets/PopularTweets/package.json
components/sp-solutions/org.wso2.carbon.sp.solutions.twitter.analytics/widgets/PopularTweets/src/PopularTweets.jsx
components/sp-solutions/org.wso2.carbon.sp.solutions.twitter.analytics/widgets/PopularTweets/src/resources/widgetConf.json

Provide refresh functionality for popular tweets widget

Twitter analytics popular tweets

---

README.md

Update Analytics-solution repository README

---

components/sp-solutions/org.wso2.carbon.sp.solutions.http.analytics/widgets/HTTPAnalyticsLatencyComparison/.eslintrc
components/sp-solutions/org.wso2.carbon.sp.solutions.http.analytics/widgets/HTTPAnalyticsLatencyComparison/package-lock.json
components/sp-solutions/org.wso2.carbon.sp.solutions.http.analytics/widgets/HTTPAnalyticsLatencyComparison/package.json
components/sp-solutions/org.wso2.carbon.sp.solutions.http.analytics/widgets/HTTPAnalyticsLatencyComparison/src/HTTPAnalyticsLatencyComparison.jsx
components/sp-solutions/org.wso2.carbon.sp.solutions.http.analytics/widgets/HTTPAnalyticsLatencyComparison/webpack.config.js

Enable eslint and refactor for HTTPAnalyticsLatencyComparison

---

components/ei-analytics-solutions/pom.xml

Remove redundant version tag.

---

components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsAttemptsByType/package-lock.json
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsAttemptsByType/package.json
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsAttemptsByType/pom.xml
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsAttemptsByType/src/IsAnalyticsAttemptsByType.jsx
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsAttemptsByType/src/resources/widgetConf.json
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsAttemptsByType/webpack.config.js
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsAttemptsOverTime/webpack.config.js
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsCompactSummary/webpack.config.js
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsLoginAttemptsMap/package-lock.json
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsLoginAttemptsMap/package.json
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsLoginAttemptsMap/pom.xml
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsLoginAttemptsMap/src/IsAnalyticsLoginAttemptsMap.jsx
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsLoginAttemptsMap/src/resources/widgetConf.json
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsLoginAttemptsMap/webpack.config.js
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsMessages/webpack.config.js
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsSummary/webpack.config.js
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsUserPreferences/webpack.config.js
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/pom.xml
features/is-analytics-feature/org.wso2.analytics.solutions.is.analytics.feature/pom.xml
features/is-analytics-feature/org.wso2.analytics.solutions.is.analytics.feature/src/main/resources/dashboards/is-analytics.json
features/is-analytics-feature/org.wso2.analytics.solutions.is.analytics.feature/src/main/resources/p2.inf
features/is-analytics-feature/org.wso2.analytics.solutions.is.analytics.feature/src/main/resources/siddhi-files/IS_AUTHENTICATION_AGGREGATIONS.siddhi
features/is-analytics-feature/org.wso2.analytics.solutions.is.analytics.feature/src/main/resources/siddhi-files/IS_AUTHENTICATION_COMMON.siddhi
features/is-analytics-feature/org.wso2.analytics.solutions.is.analytics.feature/src/main/resources/siddhi-files/IS_AUTHENTICATION_OVERALL.siddhi
pom.xml

> Closing (Issue #18 )
> Adding Is-analytics feature with siddhi apps, dashboard and the p2 file

Adding WSO2 IS Analytics feature

---

components/apim-analytics/org.wso2.analytics.solutions.apim.analytics/components/org.wso2.sp.extension.siddhi.io.mgwfile/src/main/java/org/wso2/extension/siddhi/io/mgwfile/source/MGWFileSource.java

Remove template comment to fix build.

Remove template comment to fix build.

---

components/apim-analytics/org.wso2.analytics.solutions.apim.analytics/components/org.wso2.sp.extension.siddhi.io.mgwfile/src/main/java/org/wso2/extension/siddhi/io/mgwfile/MGWFileDataRetriever.java
components/apim-analytics/org.wso2.analytics.solutions.apim.analytics/components/org.wso2.sp.extension.siddhi.io.mgwfile/src/main/java/org/wso2/extension/siddhi/io/mgwfile/MGWFileDataRetrieverThreadFactory.java
components/apim-analytics/org.wso2.analytics.solutions.apim.analytics/components/org.wso2.sp.extension.siddhi.io.mgwfile/src/main/java/org/wso2/extension/siddhi/io/mgwfile/MGWFileSourceConstants.java
components/apim-analytics/org.wso2.analytics.solutions.apim.analytics/components/org.wso2.sp.extension.siddhi.io.mgwfile/src/main/java/org/wso2/extension/siddhi/io/mgwfile/MGWFileSourceDS.java
components/apim-analytics/org.wso2.analytics.solutions.apim.analytics/components/org.wso2.sp.extension.siddhi.io.mgwfile/src/main/java/org/wso2/extension/siddhi/io/mgwfile/dao/MGWFileSourceDAO.java
components/apim-analytics/org.wso2.analytics.solutions.apim.analytics/components/org.wso2.sp.extension.siddhi.io.mgwfile/src/main/java/org/wso2/extension/siddhi/io/mgwfile/dto/MGWFileInfoDTO.java
components/apim-analytics/org.wso2.analytics.solutions.apim.analytics/components/org.wso2.sp.extension.siddhi.io.mgwfile/src/main/java/org/wso2/extension/siddhi/io/mgwfile/exception/MGWFileSourceException.java
components/apim-analytics/org.wso2.analytics.solutions.apim.analytics/components/org.wso2.sp.extension.siddhi.io.mgwfile/src/main/java/org/wso2/extension/siddhi/io/mgwfile/source/MGWFileSource.java
components/apim-analytics/org.wso2.analytics.solutions.apim.analytics/components/org.wso2.sp.extension.siddhi.io.mgwfile/src/main/java/org/wso2/extension/siddhi/io/mgwfile/task/MGWFileCleanUpTask.java
components/apim-analytics/org.wso2.analytics.solutions.apim.analytics/components/org.wso2.sp.extension.siddhi.io.mgwfile/src/main/java/org/wso2/extension/siddhi/io/mgwfile/task/MGWFileReaderTask.java
components/apim-analytics/org.wso2.analytics.solutions.apim.analytics/components/org.wso2.sp.extension.siddhi.io.mgwfile/src/main/java/org/wso2/extension/siddhi/io/mgwfile/util/FileDataRetrieverUtil.java
components/apim-analytics/org.wso2.analytics.solutions.apim.analytics/components/org.wso2.sp.extension.siddhi.io.mgwfile/src/main/java/org/wso2/extension/siddhi/io/mgwfile/util/MGWFileSourceDBUtil.java

Add license header.

---

components/apim-analytics/org.wso2.analytics.solutions.apim.analytics/components/org.wso2.sp.extension.siddhi.io.mgwfile/src/main/java/org/wso2/extension/siddhi/io/mgwfile/source/MGWFileSource.java

Adding comments to MGWEventSource

Adding comments to the EventSource

---

pom.xml

Add SCM details

---

components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsStatsChart/src/resources/widgetConf.json

Modify EIAnalyticsStatsChart widget id by removing spaces

Modify EIAnalyticsStatsChart widget id

---

features/apim-analytics-feature/org.wso2.analytics.solutions.apim.analytics.feature/src/main/resources/p2.inf

Revert 90c788c95d75f7f11b9d2b6968b99a1c0d85dcb7

---

features/apim-analytics-feature/org.wso2.analytics.solutions.apim.analytics.feature/src/main/resources/p2.inf

Add Email alert Siddhi app in APIM analytics feature.

Add Email alert Siddhi app in APIM analytics feature.

---

components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/.eslintrc
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsAttemptsByType/src/IsAnalyticsAttemptsByType.jsx
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsAttemptsOverTime/src/IsAnalyticsAttemptsOverTime.jsx
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsCompactSummary/src/IsAnalyticsCompactSummary.jsx
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsLoginAttemptsMap/package.json
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsLoginAttemptsMap/src/IsAnalyticsLoginAttemptsMap.jsx
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsMessages/src/IsAnalyticsMessages.jsx
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsSummary/src/IsAnalyticsSummary.jsx
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsUserPreferences/package.json
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsUserPreferences/src/IsAnalyticsUserPreferences.jsx
pom.xml

> Fixed ESLint issues found in widgets `jsx` files.
> Fixed UI issues such as `Material-ui` theme mismatches, and jumbling of the buttons in some widgets, using `JSS`

Fixing ES lint issues and UI issues in Widgets

---

components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsMessageTable/src/EIAnalyticsMessageTable.jsx
features/ei-analytics-feature/org.wso2.analytics.solutions.ei.analytics.feature/src/main/resources/dashboards/EI_Anlaytics_dashboard.json

Modify the EI_Analytics feature

Modify EI Analytics feature

---

components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsAttemptsByType/src/IsAnalyticsAttemptsByType.jsx
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsAttemptsOverTime/src/IsAnalyticsAttemptsOverTime.jsx
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsCompactSummary/src/IsAnalyticsCompactSummary.jsx
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsLoginAttemptsMap/src/IsAnalyticsLoginAttemptsMap.jsx
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsMessages/src/IsAnalyticsMessages.jsx
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsSummary/src/IsAnalyticsSummary.jsx
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsUserPreferences/src/IsAnalyticsUserPreferences.jsx

> Fixing alignment and text rendering issues in widgets.
> N/A

Fixing MUI theme issues in widgets

---

components/analytics-solutions-common/org.wso2.analytics.solutions.common/widgets/DateTimeRangePicker/package-lock.json
components/analytics-solutions-common/org.wso2.analytics.solutions.common/widgets/DateTimeRangePicker/package.json
components/analytics-solutions-common/org.wso2.analytics.solutions.common/widgets/DateTimeRangePicker/src/CustomTimeRangeSelector.jsx
components/analytics-solutions-common/org.wso2.analytics.solutions.common/widgets/DateTimeRangePicker/src/DateRangePicker.jsx
components/analytics-solutions-common/org.wso2.analytics.solutions.common/widgets/DateTimeRangePicker/src/DateTimePicker.jsx
components/analytics-solutions-common/org.wso2.analytics.solutions.common/widgets/DateTimeRangePicker/src/GranularityModeSelector.jsx

Widget state is used to manage query params and eslint issues are fixed.

Use widget state to manage query params

---

features/apim-analytics-feature/org.wso2.analytics.solutions.apim.analytics.feature/src/main/resources/siddhi-files/APIM_ACCESS_SUMMARY.siddhi

- Added geo location aggrgation to APIM_ACCESS_SUMMARY.siddhi

Adding Geo Stats

---

components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsAttemptsByType/src/IsAnalyticsAttemptsByType.jsx
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsAttemptsOverTime/src/IsAnalyticsAttemptsOverTime.jsx
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsCompactSummary/src/IsAnalyticsCompactSummary.jsx
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsLoginAttemptsMap/src/IsAnalyticsLoginAttemptsMap.jsx
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsMessages/src/IsAnalyticsMessages.jsx
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsSummary/src/IsAnalyticsSummary.jsx
features/is-analytics-feature/org.wso2.analytics.solutions.is.analytics.feature/src/main/resources/dashboards/is-analytics.json
features/is-analytics-feature/org.wso2.analytics.solutions.is.analytics.feature/src/main/resources/siddhi-files/IS_ANALYTICS_AUTHENTICATION_COMMON.siddhi

> Fixing IsAnalyticsAttemptsByType, IsAnalyticsLoginMap
> Updating the dashboard
> Updating siddhi app to remove using geo location data by default.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact

Fixing issues in Filter By Role and updating the dashboard

---

features/ei-analytics-feature/org.wso2.analytics.solutions.ei.analytics.feature/src/main/resources/siddhi-files/EI_Analytics_StatApp.siddhi

This will resolve primary key violations in EI related configuration tables.
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
- Ran FindSecurityBugs plugin and verified report? no
N/A
N/A
N/A
N/A
N/A

Refactoring table queries in the EI analytics siddhi app

---

pom.xml

Bump dependency versions.

---

components/analytics-solutions-common/org.wso2.analytics.solutions.common/widgets/DateTimeRangePicker/src/CustomTimeRangeSelector.jsx
components/analytics-solutions-common/org.wso2.analytics.solutions.common/widgets/DateTimeRangePicker/src/DateRangePicker.jsx
components/analytics-solutions-common/org.wso2.analytics.solutions.common/widgets/DateTimeRangePicker/src/DateTimePicker.jsx
components/analytics-solutions-common/org.wso2.analytics.solutions.common/widgets/DateTimeRangePicker/src/GranularityModeSelector.jsx

Improvements are;
1. If the time range specified in query param can't be supported with available granularity level, load the next possible time range.
2. Fix css styling

DateRangePicker Improvements

---

components/sp-solutions/org.wso2.analytics.solutions.sp.message.tracer/widgets/OpenTracingVisTimeline/src/OpenTracingVisTimeline.jsx

> To eliminate time scales getting overlap when zooming out

Enable auto scaling

---

components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsSessionCount/package-lock.json
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsSessionCount/package.json
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsSessionCountOverTime/package-lock.json
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsSessionCountOverTime/package.json
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsSessionMessages/package-lock.json
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsSessionMessages/package.json
features/is-analytics-feature/org.wso2.analytics.solutions.is.analytics.feature/src/main/resources/siddhi-files/IS_ANALYTICS_LONG_SESSION.siddhi
features/is-analytics-feature/org.wso2.analytics.solutions.is.analytics.feature/src/main/resources/siddhi-files/IS_ANALYTICS_SUSPICIOUS_LOGIN.siddhi

> Enable purging in Suspicious Login Alert Table to retain last one year records only.

Enable purging in Suspicious Login Alert Table and Long Session Alert Table.

---

features/is-analytics-feature/org.wso2.analytics.solutions.is.analytics.feature/src/main/resources/siddhi-files/IS_ANALYTICS_AUTHENTICATION_OVERALL.siddhi
features/is-analytics-feature/org.wso2.analytics.solutions.is.analytics.feature/src/main/resources/siddhi-files/IS_ANALYTICS_LONG_SESSION.siddhi
features/is-analytics-feature/org.wso2.analytics.solutions.is.analytics.feature/src/main/resources/siddhi-files/IS_ANALYTICS_SESSION_DATA.siddhi
features/is-analytics-feature/org.wso2.analytics.solutions.is.analytics.feature/src/main/resources/siddhi-files/IS_ANALYTICS_SUSPICIOUS_LOGIN.siddhi

$subject
Document trigger time

Changing trigger time of purge event as 11pm every day

---

components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsUserPreferences/src/IsAnalyticsUserPreferences.jsx

> This will fix #76 
> Also includes UX improvements, suggested by @erangatl 
> N/A

Fixing Filtering not working issue and Some UX improvements

---

components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsSessionMessages/src/IsAnalyticsSessionMessages.jsx
features/is-analytics-feature/org.wso2.analytics.solutions.is.analytics.feature/src/main/resources/dashboards/is-analytics.json

> Changing the date format in order to show the active sessions as Live

Changing the date format in Is Analytics Messages Source file

---

components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsHorizontalBarChart/package-lock.json
components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsHorizontalBarChart/package.json
components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsHorizontalBarChart/src/EIAnalyticsHorizontalBarChart.jsx
components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsMediatorProperties/package-lock.json
components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsMediatorProperties/package.json
components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsMediatorProperties/src/EIAnalyticsMediatorProperties.jsx
components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsMessageFlow/package-lock.json
components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsMessageFlow/package.json
components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsMessageFlow/src/EIAnalyticsMessageFlow.jsx
components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsMessageTable/package-lock.json
components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsMessageTable/package.json
components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsMessageTable/src/EIAnalyticsMessageTable.jsx
components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsSearchBox/package-lock.json
components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsSearchBox/package.json
components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsSearchBox/src/EIAnalyticsSearchBox.jsx
components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsSearchBox/webpack.config.js
components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsStatsChart/package-lock.json
components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsStatsChart/package.json
components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsStatsChart/src/EIAnalyticsStatsChart.jsx
components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsTPS/package-lock.json
components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsTPS/package.json
components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsTPS/src/EIAnalyticsTPS.jsx

Bump base-widget version and modify EI Analytics widgets accordingly

[EI Analytics] Bump base-widget version and modify widgets accordingly

---

features/ei-analytics-feature/org.wso2.analytics.solutions.ei.analytics.feature/src/main/resources/dashboards/ei-anlaytics-dashboard.json

Modify ei-analytics-dashboard.json, replace the dashboard with the modified generated widgets

[EI Analytics] Modify ei-analytics-dashboard.json

---

components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsMessageTable/src/resources/widgetConf.json

Changing the data provider of the EI analytics message table widget.

Refactor EI message table widget configuration

---

components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsUserPreferences/package-lock.json
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsUserPreferences/package.json

> There was an issue where buttons and input fields gets jumbled when loaded for the first time. This commit will fix it.
> N/A

Remove material-ui V0.2 from package.json

---

features/apim-analytics-feature/org.wso2.analytics.solutions.apim.analytics.feature/src/main/resources/siddhi-files/APIM_ALERT_STAKEHOLDER.siddhi

removing primary key "alertTypes"  from StakeHolder

removing primary key

---

components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsSearchBox/src/EIAnalyticsSearchBox.jsx

Fix query param handling and the issue where EI SearchBox widget doesn't render when the second value is selected.

Fix EI SearchBox widget rendering issue and query param handling

---

features/apim-analytics-feature/org.wso2.analytics.solutions.apim.analytics.feature/src/main/resources/siddhi-files/APIM_ACCESS_SUMMARY.siddhi
features/apim-analytics-feature/org.wso2.analytics.solutions.apim.analytics.feature/src/main/resources/siddhi-files/APIM_REQUEST_PROCESSOR.siddhi
features/apim-analytics-feature/org.wso2.analytics.solutions.apim.analytics.feature/src/main/resources/templates/wso2-apim-analytics.json

Adding a missed attribute to siddhi file  and changes to template

Fixing template and a siddhi file

---

components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsHorizontalBarChart/src/EIAnalyticsHorizontalBarChart.jsx
components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsHorizontalBarChart/src/resources/widgetConf.json
components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsMediatorProperties/src/resources/widgetConf.json
components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsMessageFlow/src/resources/widgetConf.json
components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsMessageTable/src/EIAnalyticsMessageTable.jsx
components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsMessageTable/src/resources/widgetConf.json
components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsSearchBox/src/resources/widgetConf.json
components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsStatsChart/src/EIAnalyticsStatsChart.jsx
components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsStatsChart/src/resources/widgetConf.json
components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsTPS/src/EIAnalyticsTPS.jsx
components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsTPS/src/resources/widgetConf.json
features/ei-analytics-feature/org.wso2.analytics.solutions.ei.analytics.feature/src/main/resources/dashboards/ei-anlaytics.json

This PR fixes widget titles in EI Analytics dashboard.

[EI Analytics] Fix widget titles

---

components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsTPS/package-lock.json
components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsTPS/package.json

Bump EIAnalyticsTPS widget to react-vizgrammar v0.7.32 to fix https://github.com/wso2/analytics-solutions/issues/108

Bump EIAnalyticsTPS widget react-vizgrammar v0.7.32

---

features/apim-analytics-feature/org.wso2.analytics.solutions.apim.analytics.feature/src/main/resources/siddhi-files/APIM_ACCESS_SUMMARY.siddhi

> Remove gateway properties from ApiLastAccessSummary table

Remove gateway properties from ApiLastAccessSummary table

---

features/is-analytics-feature/org.wso2.analytics.solutions.is.analytics.feature/src/main/resources/dashboards/is-analytics.json

> New is-analytics.json dashboard file with generated widgets

Refactoring is- analytics.json

---

components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsSessionCount/src/IsAnalyticsSessionCount.jsx
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsSessionCount/src/resources/widgetConf.json

> Source file and widgetConf.json file of IS Analytics Session Count have bee modified to make siddhiStoreDataProvider as the providerConfig type.

Use Siddhi store data provider in IsAnalyticsSessionCount widget

---

components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsSearchBox/webpack.config.js

Make react an external dependency in EIAnalyticsSearchBox widget

---

components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsAverageSessionDuration/package-lock.json
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsAverageSessionDuration/package.json
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsAverageSessionDuration/src/IsAnalyticsAverageSessionDuration.jsx
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsSessionCount/package-lock.json
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsSessionCount/package.json
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsSessionCount/src/IsAnalyticsSessionCount.jsx
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsSessionCount/src/resources/widgetConf.json
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsSessionCountOverTime/package-lock.json
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsSessionCountOverTime/package.json
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsSessionCountOverTime/src/IsAnalyticsSessionCountOverTime.jsx
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsSessionMessages/package-lock.json
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsSessionMessages/package.json
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsSessionMessages/src/IsAnalyticsSessionMessages.jsx
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsTopLongestSession/package-lock.json
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsTopLongestSession/package.json
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsTopLongestSession/src/IsAnalyticsTopLongestSession.jsx

> Refactoring widget files to avoid the issue caused by null config property

Refactoring widget files

---

features/ei-analytics-feature/org.wso2.analytics.solutions.ei.analytics.feature/src/main/resources/dashboards/ei-anlaytics.json

[EIAnalytics] Refactor dashboard widget titles

[EIAnalytics] Refactor dashboard widget titles

---

components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsMessageFlow/src/resources/widgetConf.json
features/ei-analytics-feature/org.wso2.analytics.solutions.ei.analytics.feature/src/main/resources/dashboards/ei-anlaytics.json

Modify the widget option, rename the widget into "MessageFlow" and update the ei dashboard.json

[EI Analytics] Modify EIAnalyticsMessageFlow widget

---

components/analytics-solutions-common/org.wso2.analytics.solutions.common/widgets/DateTimeRangePicker/src/CustomTimeRangeSelector.jsx

Add invalid date range message
Fixes: https://github.com/wso2/product-sp/issues/816
Node.JS v8.8.1,
NPM v5.7.1

Add invalid date range message

---

components/analytics-solutions-common/org.wso2.analytics.solutions.common/widgets/DateTimeRangePicker/src/CustomTimeRangeSelector.jsx

Fix issue where invalid dates are selected in custom range selector

Fix invalid date selection

---

components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsTPS/src/EIAnalyticsTPS.jsx

Rename EIAnalyticsTPS widget y-axis into 'TPS'

[EI Analytics] Rename EIAnalyticsTPS widget y-axis 

---

components/sp-solutions/org.wso2.analytics.solutions.sp.http.analytics/widgets/HTTPAnalyticsLatencyComparison/src/HTTPAnalyticsLatencyComparison.jsx
components/sp-solutions/org.wso2.analytics.solutions.sp.http.analytics/widgets/HTTPAnalyticsLatencyOverTime/src/HTTPAnalyticsLatencyOverTime.jsx
components/sp-solutions/org.wso2.analytics.solutions.sp.http.analytics/widgets/HTTPAnalyticsRequestCountComparison/src/HTTPAnalyticsRequestCountComparison.jsx
components/sp-solutions/org.wso2.analytics.solutions.sp.http.analytics/widgets/HTTPAnalyticsRequestCountFilter/package-lock.json
components/sp-solutions/org.wso2.analytics.solutions.sp.http.analytics/widgets/HTTPAnalyticsRequestCountOverTime/src/HTTPAnalyticsRequestCountOverTime.jsx
components/sp-solutions/org.wso2.analytics.solutions.sp.http.analytics/widgets/HTTPAnalyticsRequestStatistics/src/HTTPAnalyticsRequestStatistics.jsx
components/sp-solutions/org.wso2.analytics.solutions.sp.http.analytics/widgets/HTTPAnalyticsResponseCodeFilter/package-lock.json
components/sp-solutions/org.wso2.analytics.solutions.sp.message.tracer/widgets/OpenTracingList/src/OpenTracingList.jsx
components/sp-solutions/org.wso2.analytics.solutions.sp.twitter.analytics/widgets/EmotionsAnalysis/src/EmotionsAnalysis.jsx
components/sp-solutions/org.wso2.analytics.solutions.sp.twitter.analytics/widgets/TweetCountAnalysis/src/TweetCountAnalysis.jsx

This PR will solve intermittent issue in loading provider config in widgets.

Fixing intermittent issue in loading provider config in widgets

---

features/apim-analytics-feature/org.wso2.analytics.solutions.apim.analytics.feature/src/main/resources/siddhi-files/APIM_THROTTLED_OUT_SUMMARY.siddhi

Adding regional ID attribute to two aggregations

Adding a fix

---

pom.xml

Uptate dependency versions

---

components/sp-solutions/org.wso2.analytics.solutions.sp.message.tracer/widgets/OpenTracingVisTimeline/src/OpenTracingVisTimeline.css
components/sp-solutions/org.wso2.analytics.solutions.sp.message.tracer/widgets/OpenTracingVisTimeline/src/OpenTracingVisTimeline.jsx

Display the start time, end time and duration of message trace in trace description.

[sp-solutions][MessageTracer]Display timing details of trace

---

components/sp-solutions/org.wso2.analytics.solutions.sp.http.analytics/widgets/HTTPAnalyticsResponseCodeFilter/package-lock.json
components/sp-solutions/org.wso2.analytics.solutions.sp.http.analytics/widgets/HTTPAnalyticsResponseCodeFilter/package.json
components/sp-solutions/org.wso2.analytics.solutions.sp.http.analytics/widgets/HTTPAnalyticsResponseCodeFilter/src/HTTPAnalyticsResponseCodeFilter.jsx

The autocomplete used in response code perspective is upgraded to material ui 1.5. The drop down is rendered as a pop over so that it doesn't get hidden behind widgets beneath it.

[sp-solutions][HttpResponseCodeFilter]Upgrade search bar in response code perspective

---

components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsSearchBox/src/EIAnalyticsSearchBox.jsx
components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsSearchBox/src/resources/widgetConf.json
features/ei-analytics-feature/org.wso2.analytics.solutions.ei.analytics.feature/src/main/resources/siddhi-files/EI_Analytics_StatApp.siddhi

This PR is to fix https://github.com/wso2/analytics-solutions/issues/191
This PR will introduce a new table to EI_Analytics_StatApp that will store componentName and componentType. EIAnalyticsSearchBox widget will query this table to fetch the componentNames and populate the widget, instead of querying ESBStatAgg_MINUTES & MediatorStatAgg_MINUTES aggregations.

[EI Analytics] Modify EIAnalyticsSearchBox widget 

---

pom.xml

Bump Siddhi and Carbon Analytics version.
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? N/A
- Ran FindSecurityBugs plugin and verified report? N/A

Bump Siddhi and Carbon Analytics version.

---

components/sp-solutions/org.wso2.analytics.solutions.sp.data.search/pom.xml
components/sp-solutions/org.wso2.analytics.solutions.sp.data.search/widgets/DataSearch/package-lock.json
components/sp-solutions/org.wso2.analytics.solutions.sp.data.search/widgets/DataSearch/package.json
components/sp-solutions/org.wso2.analytics.solutions.sp.data.search/widgets/DataSearch/pom.xml
components/sp-solutions/org.wso2.analytics.solutions.sp.data.search/widgets/DataSearch/src/DataSearch.jsx
components/sp-solutions/org.wso2.analytics.solutions.sp.data.search/widgets/DataSearch/src/apis/DashboardSiddhiAppAPIs.jsx
components/sp-solutions/org.wso2.analytics.solutions.sp.data.search/widgets/DataSearch/src/chartGeneration/ChartView.jsx
components/sp-solutions/org.wso2.analytics.solutions.sp.data.search/widgets/DataSearch/src/chartGeneration/chartPropertyGenerators/GeographicalChart.jsx
components/sp-solutions/org.wso2.analytics.solutions.sp.data.search/widgets/DataSearch/src/chartGeneration/chartPropertyGenerators/LineAreaBarChart.jsx
components/sp-solutions/org.wso2.analytics.solutions.sp.data.search/widgets/DataSearch/src/chartGeneration/chartPropertyGenerators/PieChart.jsx
components/sp-solutions/org.wso2.analytics.solutions.sp.data.search/widgets/DataSearch/src/chartGeneration/chartPropertyGenerators/ScatterChart.jsx
components/sp-solutions/org.wso2.analytics.solutions.sp.data.search/widgets/DataSearch/src/chartGeneration/inputTypes/SelectProperty.jsx
components/sp-solutions/org.wso2.analytics.solutions.sp.data.search/widgets/DataSearch/src/chartGeneration/inputTypes/StreamProperty.jsx
components/sp-solutions/org.wso2.analytics.solutions.sp.data.search/widgets/DataSearch/src/chartGeneration/inputTypes/SwitchProperty.jsx
components/sp-solutions/org.wso2.analytics.solutions.sp.data.search/widgets/DataSearch/src/chartGeneration/utils/Configurations.js
components/sp-solutions/org.wso2.analytics.solutions.sp.data.search/widgets/DataSearch/src/chartGeneration/utils/Constants.js
components/sp-solutions/org.wso2.analytics.solutions.sp.data.search/widgets/DataSearch/src/chartGeneration/utils/Types.js
components/sp-solutions/org.wso2.analytics.solutions.sp.data.search/widgets/DataSearch/src/chartGeneration/utils/UtilFunctions.js
components/sp-solutions/org.wso2.analytics.solutions.sp.data.search/widgets/DataSearch/src/reportGeneration/PdfReportGenerator.jsx
components/sp-solutions/org.wso2.analytics.solutions.sp.data.search/widgets/DataSearch/src/reportGeneration/ReportConfigs.jsx
components/sp-solutions/org.wso2.analytics.solutions.sp.data.search/widgets/DataSearch/src/resources/widgetConf.json
components/sp-solutions/org.wso2.analytics.solutions.sp.data.search/widgets/DataSearch/webpack.config.js
components/sp-solutions/org.wso2.analytics.solutions.sp.data.search/widgets/assembly.xml
components/sp-solutions/org.wso2.analytics.solutions.sp.data.search/widgets/pom.xml
features/sp-solution-features/org.wso2.analytics.solutions.sp.data.search.feature/etc/feature.properties
features/sp-solution-features/org.wso2.analytics.solutions.sp.data.search.feature/pom.xml
features/sp-solution-features/org.wso2.analytics.solutions.sp.data.search.feature/src/main/resources/dashboards/datasearch.json
features/sp-solution-features/org.wso2.analytics.solutions.sp.data.search.feature/src/main/resources/p2.inf
features/sp-solution-features/pom.xml
pom.xml

> Add Data Search Feature for SP
> Select a SiddhiApp, an Aggregation or Table or a Window from the SiddhiApp and execute a query.
> View Results in a Table Chart
> Export the Table as PDF
> Generate charts using the result
> Export charts as PDF
> Get  Siddhi apps which have @store annotated Aggregation, Table or Window using the Dashboard Siddhi Apps Api
> Get Aggregations, Tables and Windows from the selected Siddhi App
> Get Results for the query using SiddhiDataProvider
>Add worker list in the dashboard deployment.yaml under wso2.dashboards.datasearch
>wso2.dashboard.datasearch:
>&nbsp;&nbsp;&nbsp;workerList:
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- localhost:9443
>&nbsp;&nbsp;&nbsp;workerAccessCredentials:
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;username: admin …

Add Data Search Feature for SP

---

components/apim-analytics/org.wso2.analytics.solutions.apim.analytics/widgets/APIMOverallApiStats/pom.xml
components/apim-analytics/org.wso2.analytics.solutions.apim.analytics/widgets/APIMTopApiCreators/pom.xml
components/apim-analytics/org.wso2.analytics.solutions.apim.analytics/widgets/APIMTopAppCreators/pom.xml
components/apim-analytics/org.wso2.analytics.solutions.apim.analytics/widgets/APIMTopSubscribers/pom.xml

Fix build.

---

pom.xml

Bump Siddhi & Siddhi extension versions.

Bump Siddhi & Siddhi extension versions.

---

components/sp-solutions/org.wso2.analytics.solutions.sp.message.tracer/widgets/OpenTracingVisTimeline/package-lock.json
components/sp-solutions/org.wso2.analytics.solutions.sp.message.tracer/widgets/OpenTracingVisTimeline/package.json
components/sp-solutions/org.wso2.analytics.solutions.sp.message.tracer/widgets/OpenTracingVisTimeline/src/OpenTracingVisTimeline.css
components/sp-solutions/org.wso2.analytics.solutions.sp.message.tracer/widgets/OpenTracingVisTimeline/src/OpenTracingVisTimeline.jsx

> Improve UI of Tracing TimeLine Widget
> -Display service name and operation name
> -Add spankind badge
> -Add horizontal resizability for timeline
> -Add min,  max values for timeline and limit it
> -Display duration next to the span
> -Improve description table style
> -Improve timeline style
Before
After

[sp-solutions][MessageTracer] Improve TimeLine UI 

---

components/sp-solutions/org.wso2.analytics.solutions.sp.data.search/widgets/DataSearch/src/DataSearch.jsx
components/sp-solutions/org.wso2.analytics.solutions.sp.data.search/widgets/DataSearch/src/reportGeneration/PdfReportGenerator.jsx
features/sp-solution-features/org.wso2.analytics.solutions.sp.data.search.feature/src/main/resources/dashboards/datasearch.json

> Currently default style is used for the table result report. Custom style need to be added.
> Add style for table result report.

[DataSearch] Add Custom Style for TablePDF

---

features/apim-analytics-feature/org.wso2.analytics.solutions.apim.analytics.feature/src/main/resources/siddhi-files/apim_unusual_ip_access_alert_0.siddhi

> Fix wrong written siddhi app apim_unusual_ip_access_alert_0.siddhi
> Correctly deploy siddhi app, apim_unusual_ip_access_alert_0.siddhi 

Fix wrong written siddhi app in APIM Analytics

---

components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsMessageFlow/src/EIAnalyticsMessageFlow.jsx

> Fix #218 zoomIn, zoomOut, zoomFit buttons don't work.

[EIAnalytics] [MessageFlow] Fix zoomIn, zoomOut, zoomFit buttons

---

features/apim-analytics-feature/org.wso2.analytics.solutions.apim.analytics.feature/src/main/resources/siddhi-files/APIM_ACCESS_SUMMARY.siddhi

$subject
Fixes https://github.com/wso2/analytics-solutions/issues/214
N/A

Introduce 1 sec buffer to insert to ApiLastAccessSummary

---

components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsAttemptsByType/package.json
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsAttemptsOverTime/package.json
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsAverageSessionDuration/package.json
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsCompactSummary/package.json
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsLoginAttemptsMap/package.json
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsMessages/package.json
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsSessionCount/package.json
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsSessionCountOverTime/package.json
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsSessionMessages/package.json
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsSummary/package.json
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsTopLongestSession/package.json

Bump React-VizGrammar to latest version V0.8.4 in IS Analytics

Bump React-VizGrammar to latest version V0.8.4 in IS Analytics

---

features/ei-analytics-feature/org.wso2.analytics.solutions.ei.analytics.feature/src/main/resources/siddhi-files/EI_Analytics_StatApp.siddhi

$subject, Fixes https://github.com/wso2/analytics-solutions/issues/208
N/A

Convert purging filter attribute to long

---

features/ei-analytics-feature/org.wso2.analytics.solutions.ei.analytics.feature/src/main/resources/dashboards/ei-anlaytics.json

> Fix https://github.com/wso2/analytics-solutions/issues/251
> Fix #229 
> Add human readable timestamp in the tooltip.
> Realign widgets and optimize dashboard pages.

[EIAnalytics] [Generated Widgets] Add readable timestamp and realign height

---

components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsHorizontalBarChart/package.json
components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsStatsChart/package.json
components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsTPS/package.json

[EIAnalytics] [Widgets] Bump react-vizgrammar version

---

components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsStatsChart/src/EIAnalyticsStatsChart.jsx

[EIAnalytics] [StatsChart] Check if there is data before setting the state

---

components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsMessageFlow/src/EIAnalyticsMessageFlow.jsx

[EIAnalytics] [MessageFlow] Check if data array is not empty 

---

components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsTPS/src/EIAnalyticsTPS.jsx

[EIAnalytics] [OverallTPS] Set X axis label timeFormat according to granularity

---

components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsAttemptsByType/package.json
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsAttemptsByType/src/IsAnalyticsAttemptsByType.jsx
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsAttemptsOverTime/src/IsAnalyticsAttemptsOverTime.jsx
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsCompactSummary/src/IsAnalyticsCompactSummary.jsx
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsSummary/src/IsAnalyticsSummary.jsx
components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsUserPreferences/src/IsAnalyticsUserPreferences.jsx
features/is-analytics-feature/org.wso2.analytics.solutions.is.analytics.feature/src/main/resources/dashboards/is-analytics.json

Fix IS Analytics dashboard UI issues
This will fix UI issues to improve chart visibility.

Fix IS Analytics dashboard UI issues

---

components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsTPS/src/EIAnalyticsTPS.jsx

> Rename Y Axis label as Average TPS

[EIAnalytics] [EIAnalyticsTPS] Rename Y Axis label as Average TPS

---

features/ei-analytics-feature/org.wso2.analytics.solutions.ei.analytics.feature/src/main/resources/siddhi-files/EI_Analytics_StatApp.siddhi

> Add @PartitionById for MediatorStatAgg and ESBStatAgg
> Change Insert Queries for ComponentNameInMemoryTable and ComponentNameTable

[EIAnalytics] Add changes in EIAnalytics Siddhi App

---

features/apim-analytics-feature/org.wso2.analytics.solutions.apim.analytics.feature/src/main/resources/siddhi-files/APIM_ACCESS_SUMMARY.siddhi
features/apim-analytics-feature/org.wso2.analytics.solutions.apim.analytics.feature/src/main/resources/siddhi-files/APIM_PERSIST_ALERTS.siddhi
features/apim-analytics-feature/org.wso2.analytics.solutions.apim.analytics.feature/src/main/resources/siddhi-files/apim_alert_health_availability_0.siddhi
features/apim-analytics-feature/org.wso2.analytics.solutions.apim.analytics.feature/src/main/resources/siddhi-files/apim_alert_unusual_ip_access_0.siddhi

Reducing buffer sizes for memory optimisation

---

pom.xml

Fix dependency versions

---

pom.xml

Upgrade carbon-analytics dependency

---

features/apim-analytics-feature/org.wso2.analytics.solutions.apim.analytics.feature/src/main/resources/siddhi-files/APIM_PERSIST_ALERTS.siddhi

$subject in https://github.com/wso2/analytics-solutions/pull/271
N/A

Add missed alert event tables

---

components/apim-analytics/org.wso2.analytics.solutions.apim.analytics/components/org.wso2.sp.extension.siddhi.io.mgwfile/src/main/java/org/wso2/extension/siddhi/io/mgwfile/MGWFileSourceDS.java

$Subject. This component looks for MGW datasource at activation and currently component activation layer is not profile aware. Because of that we can't stop the component based on the profile. Hence we are improving the logging.

Improve logging messages to make users aware of the impact of the error

---

components/apim-analytics/org.wso2.analytics.solutions.apim.analytics/components/org.wso2.sp.extension.siddhi.io.mgwfile/src/main/java/org/wso2/extension/siddhi/io/mgwfile/MGWFileSourceDS.java

Fix build failure

---

pom.xml

Update carbon-solutions dependencies

---

components/apim-analytics/org.wso2.analytics.solutions.apim.analytics/components/org.wso2.sp.extension.siddhi.io.mgwfile/src/main/java/org/wso2/extension/siddhi/io/mgwfile/MGWFileDataRetriever.java

> This code did not have an else block to indicate an error. In addition, the uploaded file name is similar to **/home/user/wso2am-cloud-micro-gw-2.6.0-hybrid/api-usage-data/api-usage-data.dat**, but the string match fails to identify that and skipping the file. 
> Bug fix hybrid-gateway file uploading issue
> Split the string and read only the zip file name.
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- Unit tests 
> Code coverage information
- Integration tests
> Details about the test cases and coverage
> Provide high-level …

Fix hybrid-gateway analytics file processing issue

---

features/apim-analytics-feature/org.wso2.analytics.solutions.apim.analytics.feature/src/main/resources/siddhi-files/APIM_ACCESS_SUMMARY.siddhi
features/apim-analytics-feature/org.wso2.analytics.solutions.apim.analytics.feature/src/main/resources/siddhi-files/APIM_FAULT_SUMMARY.siddhi
features/apim-analytics-feature/org.wso2.analytics.solutions.apim.analytics.feature/src/main/resources/siddhi-files/APIM_THROTTLED_OUT_SUMMARY.siddhi

$subject. fixes https://github.com/wso2/analytics-solutions/issues/290
N/A

Fix update error when of order events are received

---

pom.xml

Bump carbon-analytics version

---

pom.xml

Fix typo in pom.xml

---

features/apim-analytics-feature/org.wso2.analytics.solutions.apim.analytics.feature/src/main/resources/email-notification-siddhi-file/APIM_ALERT_EMAIL_NOTIFICATION.siddhi

This fix resolves the issue in email alerts triggers for all tenants.
https://github.com/wso2/analytics-apim/issues/609
Avoid emails being sent across tenants
EmailAlertStream is filtered by tenancy domain
N/A

Fix email issue in siddhi app

---

features/apim-analytics-feature/org.wso2.analytics.solutions.apim.analytics.feature/src/main/resources/siddhi-files/APIM_EVENT_RECEIVER.siddhi

$subject to prevent data being larger than the coloumn size
N/A

Truncate throttle stream

---

components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsAttemptsByType/src/IsAnalyticsAttemptsByType.jsx

Fix formatting

---

components/apim-analytics/org.wso2.analytics.solutions.apim.analytics/widgets/APIMApiBackendUsageSummary/src/APIMApiBackendUsage.jsx
components/apim-analytics/org.wso2.analytics.solutions.apim.analytics/widgets/APIMApiLastAccessSummary/src/APIMApiLastAccess.jsx
components/apim-analytics/org.wso2.analytics.solutions.apim.analytics/widgets/APIMApiLatencyTime/src/APIMApiLatency.jsx
components/apim-analytics/org.wso2.analytics.solutions.apim.analytics/widgets/APIMApiResourceUsageSummary/src/APIMApiResourceUsage.jsx
components/apim-analytics/org.wso2.analytics.solutions.apim.analytics/widgets/APIMApiResponseSummary/src/APIMApiResponse.jsx
components/apim-analytics/org.wso2.analytics.solutions.apim.analytics/widgets/APIMApiVersionUsageSummary/src/APIMApiVersionUsage.jsx
components/apim-analytics/org.wso2.analytics.solutions.apim.analytics/widgets/APIMGeoBasedInvocations/src/APIMGeoInvocations.jsx
components/apim-analytics/org.wso2.analytics.solutions.apim.analytics/widgets/APIMTopApiUsers/src/APIMTopApiUsers.jsx
components/apim-analytics/org.wso2.analytics.solutions.apim.analytics/widgets/APIMTopPlatforms/src/APIMTopPlatforms.jsx
components/apim-analytics/org.wso2.analytics.solutions.apim.analytics/widgets/APIMTopUserAgents/src/APIMTopAgents.jsx

Update menu item values

---

components/analytics-solutions-common/org.wso2.analytics.solutions.common/widgets/DateTimeRangePicker/src/widget/components/CustomTimeRangeSelector.jsx
components/analytics-solutions-common/org.wso2.analytics.solutions.common/widgets/DateTimeRangePicker/src/widget/components/TimePicker.jsx
components/sp-solutions/org.wso2.analytics.solutions.sp.twitter.analytics/widgets/PopularTweets/src/PopularTweets.jsx

Refactor per review 
- https://github.com/wso2/analytics-solutions/pull/164
- https://github.com/wso2/analytics-solutions/pull/9
- https://github.com/wso2/analytics-solutions/pull/148

Refactor as per PR reviews 

---

components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsHorizontalBarChart/src/EIAnalyticsHorizontalBarChart.jsx
components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsMediatorProperties/src/EIAnalyticsMediatorProperties.jsx
components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsMessageFlow/src/EIAnalyticsMessageFlow.jsx
components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsMessageTable/src/EIAnalyticsMessageTable.jsx
components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsSearchBox/src/EIAnalyticsSearchBox.jsx
components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsStatsChart/src/EIAnalyticsStatsChart.jsx
components/ei-analytics/org.wso2.analytics.solutions.ei.analytics/widgets/EIAnalyticsTPS/src/EIAnalyticsTPS.jsx
pom.xml

This PR is to update EI analytics widgets to be compatible with analytics-dashboard 1.0.0 and upgrade siddhi version

Update EI analytics widgets

---

features/analytics-solutions-common-features/org.wso2.analytics.solutions.common.feature/src/main/resources/p2.inf

This is to change the feature widget location to make it compatible with analytics dashboard
portal->analytics-dashboard

Change the feature widget location

---

components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsLoginAttemptsMap/package.json

**Fixes: https://github.com/wso2/product-is/issues/9521**

react-vizgrammar version bumped in Map widget

---

components/is-analytics/org.wso2.analytics.solutions.is.analytics/widgets/IsAnalyticsAverageSessionDuration/src/resources/widgetConf.json

AverageSessionDuration Aggregation widget is not working

---

features/is-analytics-feature/org.wso2.analytics.solutions.is.analytics.feature/src/main/resources/siddhi-files/IS_ANALYTICS_LONG_SESSION.siddhi

Resolves https://github.com/wso2/product-is/issues/11516

Fix NPE in worker node for LeadersLastSevenDaysStream stream

---

features/ei-analytics-feature/org.wso2.analytics.solutions.ei.analytics.feature/src/main/resources/dashboards/ei-anlaytics.json

Rename dashboard name to Micro integrator analytics

Rename dashboard name
